# Generated by Django 2.0.5 on 2018-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_school_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30, unique=True)),
                ('teacher', models.ManyToManyField(to='app01.Teacher')),
            ],
        ),
    ]
